### ISSUE TITLE
could not determine kind of name for C.veinmind_TarballLoad?

### ISSUE THREAD

**Issue by himywei** [chaitin/libveinmind#38]
when i try to use libveinmind sdk, the following problems occurred:

  # github.com/chaitin/libveinmind/go/pkg/binding
  /home/xxx/GolangProjects/pkg/mod/github.com/chaitin/libveinmind@v1.3.0/go/pkg/binding/functions.go:650:24: could not determine kind of name for C.veinmind_TarballLoad
  /home/xxx/GolangProjects/pkg/mod/github.com/chaitin/libveinmind@v1.3.0/go/pkg/binding/functions.go:641:24: could not determine kind of name for C.veinmind_TarballNew
  /home/xxx/GolangProjects/pkg/mod/github.com/chaitin/libveinmind@v1.3.0/go/pkg/binding/functions.go:659:24: could not determine kind of name for C.veinmind_TarballRemoveImageByID

env： WSL2/ubuntu 20.04

**Comment by d1nfinite** [comment]
fixed, please retry to install libveinmind
